### Hämta alla personer
GET http://localhost:8080/api/data
Accept: application/json

### Limitera data till fem rader
GET http://localhost:8080/api/data?limit=5
Accept: application/json

### Försök att limitera data med negativt heltal (bör returnera 400 Bad Request)
GET http://localhost:8080/api/data?limit=-5
Accept: application/json

### Försök att limitera data med något annat än ett heltal (bör returnera 400 Bad Request)
GET http://localhost:8080/api/data?limit=abc
Accept: application/json
